import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f1",
        "surface-dim": "#e1d9cc",
        "surface-bright": "#fff8f1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#faf2e9",
        "surface-container": "#f5ede2",
        "surface-container-high": "#efe7db",
        "surface-container-highest": "#eae1d4",
        "surface-variant": "#eae1d4",
        "surface-tint": "#974362",
        "on-surface": "#363229",
        "on-surface-variant": "#645e54",
        "on-background": "#363229",
        "background": "#fff8f1",
        "primary": "#974362",
        "primary-dim": "#883756",
        "primary-container": "#fe97b9",
        "primary-fixed": "#fe97b9",
        "primary-fixed-dim": "#ee8aac",
        "on-primary": "#fff7f7",
        "on-primary-container": "#621837",
        "on-primary-fixed": "#420020",
        "on-primary-fixed-variant": "#6d2140",
        "secondary": "#69558e",
        "secondary-dim": "#5c4981",
        "secondary-container": "#ebdcff",
        "secondary-fixed": "#ebdcff",
        "secondary-fixed-dim": "#dfccff",
        "on-secondary": "#fef7ff",
        "on-secondary-container": "#5b487f",
        "on-secondary-fixed": "#48356b",
        "on-secondary-fixed-variant": "#65518a",
        "tertiary": "#7d5817",
        "tertiary-dim": "#704c0a",
        "tertiary-container": "#ffcc80",
        "tertiary-fixed": "#ffcc80",
        "tertiary-fixed-dim": "#f0be74",
        "on-tertiary": "#fff8f2",
        "on-tertiary-container": "#644200",
        "on-tertiary-fixed": "#4b3100",
        "on-tertiary-fixed-variant": "#6f4c09",
        "outline": "#807a6f",
        "outline-variant": "#b9b1a5",
        "error": "#a8364b",
        "error-dim": "#6b0221",
        "error-container": "#f97386",
        "on-error": "#fff7f7",
        "on-error-container": "#6e0523",
        "inverse-surface": "#100e0a",
        "inverse-on-surface": "#a19c95",
        "inverse-primary": "#fe97b9",
      },
      fontFamily: {
        "headline": ["var(--font-jua)", "sans-serif"],
        "body": ["var(--font-pretendard)", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
      },
    },
  },
  plugins: [],
};

export default config;
